name: Image Scanner

on:
  workflow_call:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  scan-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build image
        run: docker build --pull --no-cache -t flask-devsecops-pipeline:${{ github.sha }} .

      - name: Scan image with Trivy
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "${{ github.workspace }}:/workspace" \
            aquasec/trivy:latest image \
            --ignore-unfixed \
            --severity HIGH,CRITICAL \
            --format table \
            --exit-code 1 \
            --ignorefile /workspace/.trivyignore \
            flask-devsecops-pipeline:${{ github.sha }}
