name: Secrets Scan

on:
  workflow_call:

jobs:
  secrets-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Gitleaks CLI
        run: |
          curl -sSfL https://raw.githubusercontent.com/gitleaks/gitleaks/master/install.sh \
            | sh -s -- -b /usr/local/bin

      - name: Run Gitleaks
        run: gitleaks detect --source . --verbose --redact --exit-code 1
